# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05c258bc90149ef946e386e50ed78695b5cededa2cfb7874a4a749c164c7ece4d8ffe342c2a8e94e843603db25a20711de719a0c193ccf8404e49e55d1e0da4d

test:
  secret_key_base: ff4ceb8ecaaec8b600dbcf34a273d4e67a3b87dafb10b1d9471520a91d48ca3b50b88b7cbe5f6aef59c6a2ba564b4e463f43cf14e59189ad3a444ecc3c011d16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
